apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
- tests

replacements:
- source:
    kind: Service
    name: bmmi-db
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=php-apache].env.[name=DATABASE_HOST].value
    select:
      kind: Deployment
      name: bmmi-web
- source:
    kind: Service
    name: bmmi-web
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=curl].env.[name=WEB_TARGET].value
    select:
      kind: Job
- source:
    fieldPath: spec.ports.[name=http].port
    kind: Service
    name: bmmi-web
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=curl].env.[name=WEB_PORT].value
    select:
      kind: Job

images:
- name: karstensiemer/bmmi
  newName: karstensiemer/bmmi-pr
  newTag: f9cb46ff9ec22f04377dd16e54fa2f27b4623b7b
