apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
- tests

replacements:
- source:
    kind: Service
    name: bmmi-db
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=php-apache].env.[name=DATABASE_HOST].value
    select:
      kind: Deployment
      name: bmmi-web

images:
- name: karstensiemer/bmmi
  newName: karstensiemer/bmmi-pr
  newTag: d7cca83484a995ff181900ad81ba2f79ff31b5df
