apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
- tests
images:
- name: karstensiemer/bmmi
  newName: karstensiemer/bmmi-pr
  newTag: ce6686afb02fcde0d6aeecbb6b4bc2e843623e20
