repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: mixed-line-ending
      args: [ --fix=lf ]
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=* ]
    - id: check-merge-conflict
    - id: detect-aws-credentials
      args: [ --allow-missing-credentials ]
    - id: double-quote-string-fixer
    - id: end-of-file-fixer

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shellcheck

- repo: local
  hooks:
    - id: run-tests
      name: run-tests
      description: "Run php test frameworks"
      always_run: true
      entry: run-tests.bash
      language: script
      types: [bash]
      pass_filenames: false

- repo: local
  hooks:
    - id: run-reconcile
      name: run-reconcile
      description: "Update dump file for git release"
      always_run: true
      entry: run-reconcile.bash
      language: script
      types: [bash]
      pass_filenames: false

- repo: https://github.com/sqlfluff/sqlfluff
  rev: 1.4.2
  hooks:
    - id: sqlfluff-lint
      args: [ --dialect=mysql ]
    - id: sqlfluff-fix
      args: [ --dialect=mysql ]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
    - id: markdownlint
      args: [ --disable=MD013 ]
