plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - - '@semantic-release/changelog'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG-TEMP.md
  - - '@semantic-release/exec'
    - prepareCmd: './publish_release.bash "${nextRelease.version}" "${nextRelease.type}" "releases" "CHANGELOG-TEMP.md"'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - releases/*.md
      message: "docs(changelog): ${nextRelease.version} \n\n${nextRelease.notes}"
  - '@semantic-release/github'
