plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - 'conventional-changelog-conventionalcommits'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
      message: "docs(changelog): ${nextRelease.version} \n\n${nextRelease.notes}"
