plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - - '@semantic-release/changelog'
    - changelogTitle: \# CHANGELOG
  - - '@semantic-release/exec'
    - publishCmd: './publish_release.bash "${nextRelease.version}" "${nextRelease.notes}" "${Date.now()"'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - releases/*.md
      message: "docs(changelog): ${nextRelease.version} \n\n${nextRelease.notes}"
  - '@semantic-release/github'
