version: '3.9'
services:
  web:
    container_name: bmmi-web
    image: webdevops/php-apache:8.4
    restart: unless-stopped
    ports:
      - 4443:443
      - 4080:80
    environment:
      WEB_DOCUMENT_INDEX: index.html
      WEB_ALIAS_DOMAIN: bmmi.local.127.0.0.1.nip.io
      DATABASE: '${DATABASE}'
      DATABASE_HOST: 'database'
      DATABASE_PORT: '3306'
      DATABASE_USER: '${DATABASE_USER}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - './app:/app'
    networks:
      - bmmi-net
    links:
      - 'db:database'
  db:
    container_name: bmmi-db
    image: mariadb:11.6.2
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'
      MARIADB_DATABASE: '${DATABASE}'
      MARIADB_USER: '${DATABASE_USER}'
      MARIADB_PASSWORD: '${DATABASE_PASSWORD}'
      MARIADB_AUTO_UPGRADE: 'true'
    volumes:
      - 'bmmi-db:/var/lib/mysql'
    networks:
      - bmmi-net

networks:
  bmmi-net:

volumes:
  bmmi-db:
