---
apiVersion: v1
kind: Service
metadata:
  name: bmmi-db
  labels:
    app: bmmi-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
    - port: 33060
      name: mysqlx
      targetPort: 33060
  clusterIP: None # Headless service
  selector:
    app: bmmi-db
