apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bmmi-pr
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - pullRequest:
        github:
          owner: KarstenSiemer
          repo: BMMI
          tokenRef:
            secretName: argocd-secret
            key: webhook.github.secret
          labels:
            - deploy
        requeueAfterSeconds: 30
  template:
    metadata:
      name: 'bmmi-pr-{{.number}}'
      annotations:
        link.argocd.argoproj.io/external-link: http://bmmi-pr-{{.number}}.dev.127.0.0.1.nip.io:7080
    spec:
      project: 'dev'
      source:
        repoURL: git@github.com:KarstenSiemer/BMMI.git
        targetRevision: '{{.head_sha}}'
        path: 'deploy/kustomize/overlays/pr'
        kustomize:
          nameSuffix: -pr-{{.number}}
          commonLabels:
            app.kubernetes.io/instance: 'pr-{{.number}}'
          commonAnnotationsEnvsubst: true
          commonAnnotations:
            app-source: ${ARGOCD_APP_NAME}
          patches:
            - target:
                kind: Deployment
                name: bmmi
              patch: |-
                - op: replace
                  path: "/spec/template/spec/containers/0/env/-"
                  value:
                    name: WEB_ALIAS_DOMAIN
                    value: bmmi-pr-{{.number}}.dev.127.0.0.1.nip.io
            - target:
                kind: Job
              patch: |-
                - op: replace
                  path: "/spec/template/spec/containers/0/env/-"
                  value:
                    name: WEB_ALIAS_DOMAIN
                    value: bmmi-pr-{{.number}}.dev.127.0.0.1.nip.io
            - target:
                kind: Ingress
                name: bmmi
              patch: |-
                - op: replace
                  path: /spec/rules/0/host
                  value: bmmi-pr-{{.number}}.dev.127.0.0.1.nip.io
      destination:
        name: dev
        namespace: bmmi-pr-{{.number}}
      info:
        - name: 'PR'
          value: '{{.number}}'
        - name: 'Labels'
          value: '{{.labels}}'
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/instance: 'bmmi-pr-{{.number}}'
          annotations:
            argocd.argoproj.io/tracking-id: >-
              'bmmi-pr-{{.number}}:app/Namespace:bmmi-pr-{{.number}}/bmmi-pr-{{.number}}
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
