---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmmi-web
  annotations:
    kube-score/ignore: pod-networkpolicy,container-ephemeral-storage-request-and-limit,container-security-context-readonlyrootfilesystem,container-security-context-user-group-id,container-security-context-privileged,container-security-context-readonlyrootfilesystem
  labels:
    app: bmmi-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmmi-web
  template:
    metadata:
      labels:
        app: bmmi-web
    spec:
      containers:
        - name: php-apache
          image: karstensiemer/bmmi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
            - name: WEB_DOCUMENT_INDEX
              value: 'index.html'
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: bmmi-db
                  key: DATABASE
            - name: DATABASE_HOST
              value: bmmi-db
            - name: DATABASE_PORT
              value: '3306'
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: bmmi-db
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bmmi-db
                  key: DATABASE_PASSWORD
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '250m'
          securityContext:
            capabilities:
              drop: ['ALL']
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 5
