apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"

images:
- name: karstensiemer/bmmi
  newTag: 1.7.9@sha256:3a9f1bf70b126057c48fc6167daa999461b148ea429320bfb43e19c504baa491
