name: Build

on:
  pull_request:
    branches: ['main']
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  docker:
    if: contains(github.event.pull_request.labels.*.name, 'build')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: karstensiemer/bmmi-pr:${{ github.sha }}
      - uses: yokawasa/action-setup-kube-tools@v0.11.1
        with:
          kustomize: '5.5.0'
      - name: Change PR image sha
        run: |
          cd deploy/kustomize/overlays/pr
          kustomize edit set image karstensiemer/bmmi=karstensiemer/bmmi-pr:${{ github.sha }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'fix(pr): set pr overlay image'
          commit_options: '--no-verify --signoff'
          add_options: '-u'
      - uses: actions/labeler@v5
