name: Build

env:
  LABELS: ''
  LABEL: 'build'

on:
  pull_request:
    types: [synchronize, opened]
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/get-labels-action@v1
      - name: Checkout
        if: contains(fromJSON(env.LABELS), env.LABEL)
        uses: actions/checkout@v4
      - name: Set up QEMU
        if: contains(fromJSON(env.LABELS), env.LABEL)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: contains(fromJSON(env.LABELS), env.LABEL)
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: contains(fromJSON(env.LABELS), env.LABEL)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: contains(fromJSON(env.LABELS), env.LABEL)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: karstensiemer/bmmi-pr:${{ github.sha }}
      - uses: yokawasa/action-setup-kube-tools@v0.11.1
        if: contains(fromJSON(env.LABELS), env.LABEL)
        with:
          kustomize: '5.5.0'
      - name: Change PR image sha
        if: contains(fromJSON(env.LABELS), env.LABEL)
        run: |
          cd deploy/kustomize/overlays/pr
          kustomize edit set image karstensiemer/bmmi=karstensiemer/bmmi-pr:${{ github.sha }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: contains(fromJSON(env.LABELS), env.LABEL)
        with:
          commit_message: 'fix(pr): set pr overlay image'
          commit_options: '--no-verify --signoff'
          add_options: '-u'
      - uses: actions/labeler@v5
        if: contains(fromJSON(env.LABELS), env.LABEL)
