name: Kustomize

env:
  LABELS: ''
  LABEL: 'kustomize'

on:
  pull_request:
    types: [synchronize, opened]
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: snnaplab/get-labels-action@v1
      - name: Checkout
        if: contains(fromJSON(env.LABELS), env.LABEL)
        uses: actions/checkout@v4
      - uses: yokawasa/action-setup-kube-tools@v0.11.1
        if: contains(fromJSON(env.LABELS), env.LABEL)
        with:
          kustomize: '5.5.0'
          kube-score: '1.19.0'
      - name: Check manifest for validity
        if: contains(fromJSON(env.LABELS), env.LABEL)
        run: |
          # Check if yamls are kustomizable and compliant
          find deploy/kustomize -type f -name \
            "kustomization.yaml" | xargs -S1024 -P 4 -I {} sh -c \
            'kustomize build "$(dirname {})" | \
            kube-score score \
              --ignore-test pod-networkpolicy \
              --ignore-test container-ephemeral-storage-request-and-limit \
              --ignore-test container-security-context-readonlyrootfilesystem \
              --ignore-test container-security-context-user-group-id \
              --ignore-test container-security-context-privileged \
              --ignore-test container-security-context-readonlyrootfilesystem - ' \
            || exit 1
