name: PreCommit

on:
  pull_request:
    branches: ['main']

permissions: read-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          kustomize: '5.5.0'
          kube-score: '1.19.0'
      - uses: pre-commit/action@v3.0.1
