name: PreCommit

on:
  pull_request:
    branches: ['main']

permissions: read-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
