name: Release

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
    branches: ['main']

permissions:
  contents: write
  issues: write
  pull-requests: write
  checks: write
  statuses: write

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
      - name: Semantic Release Dry Run
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-dry
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@6
          dry_run: true
      - name: Set up QEMU
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
      - name: Set up Docker Buildx
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
      - name: Login to Docker Hub
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: karstensiemer/bmmi:${{ steps.semantic-dry.outputs.new_release_version }}
      - uses: yokawasa/action-setup-kube-tools@9e25a4277af127b60011c95b6ed2da7e3b3613b1 # v0.11.2
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        with:
          kustomize: '5.5.0'
      - name: Change Core Image
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        run: |
          echo "Setting base/core to current release"
          cd deploy/kustomize/base/core
          kustomize edit set image karstensiemer/bmmi=:${{ steps.semantic-dry.outputs.new_release_version }}
          echo "Resetting overlays/pr to current release to be up to date for next PR"
          cd ../../overlays/pr
          kustomize edit set image karstensiemer/bmmi=:${{ steps.semantic-dry.outputs.new_release_version }}
      - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        with:
          commit_message: 'fix(core): set bmmi release image to ${{ steps.semantic-dry.outputs.new_release_version }}'
          commit_options: '--no-verify --signoff'
          add_options: '-u'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@6
