name: Release

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
    branches: ['main']

permissions:
  contents: write
  issues: read

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Semantic Release Dry Run
        uses: cycjimmy/semantic-release-action@v4
        id: semantic-dry
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@6
          dry_run: true
      - name: Set up QEMU
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: karstensiemer/bmmi:${{ steps.semantic-dry.outputs.new_release_version }}
      - uses: yokawasa/action-setup-kube-tools@v0.11.1
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        with:
          kustomize: '5.5.0'
      - name: Change PR image sha
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        run: |
          echo "Setting base/core to current release"
          cd deploy/kustomize/base/core
          kustomize edit set image karstensiemer/bmmi=:${{ steps.semantic-dry.outputs.new_release_version }}
          echo "Resetting overlays/pr to current release to be up to date for next PR"
          cd ../../overlays/pr
          kustomize edit set image karstensiemer/bmmi=:${{ steps.semantic-dry.outputs.new_release_version }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.semantic-dry.outputs.new_release_published == 'true'
        with:
          commit_message: 'fix(core): set bmmi release image to ${{ steps.semantic-dry.outputs.new_release_version }}'
          commit_options: '--no-verify --signoff'
          add_options: '-u'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@6
